### ISSUE TITLE
Get bank details

### ISSUE THREAD

**Issue by ebd1004alu** [mqd1001/Practica-2-gespro#33]

**Comment by edf1003** [comment]
¿Qué tipo de datos se mostrarán?

**Comment by mqd1001** [comment]
> ¿Qué tipo de datos se mostrarán?
Datos como la ubicación del banco, el número de usuarios, de trabajadores... es decir, información relevante para el usuario a la hora de escoger banco.

**Comment by bae1001** [comment]
¿Se mostrarán muchos datos?

**Comment by mqd1001** [comment]
> ¿Se mostrarán muchos datos?

Solo los más relevantes, para no agobiar al usuario con información innecesaria.
