### ISSUE TITLE
Manage the app from an iPhone

### ISSUE THREAD

**Issue by mqd1001** [mqd1001/Practica-2-gespro#8]

**Comment by mqd1001** [comment]
¿Y desde Android?

**Comment by edf1003** [comment]
¿Y desde Android?

**Comment by mqd1001** [comment]
> ¿Y desde Android?

No será posible, al menos no en corto plazo.

**Comment by bae1001** [comment]
¿Es difícil manejar la aplicación desde IPhone?

**Comment by mqd1001** [comment]
> ¿Es difícil manejar la aplicación desde IPhone?

No. La aplicación está diseñada para que la puedan utilizar usuarios sin demasiada experiencia. Además, contará con un videotutorial así como una ayuda siempre disponible.
